version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    groups:
      test-dependencies:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
      packet-dependencies:
        patterns:
          - "SharpPcap"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
